# Generated by Django 5.2.8 on 2025-11-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='nombre_rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario'), ('Jefe Bodega', 'Jefe Bodega')], default='Usuario', max_length=20, unique=True),
        ),
    ]
