# Generated by Django 5.2.8 on 2025-11-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='roles',
            name='permisos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
