# Generated by Django 5.2.8 on 2025-11-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_roles_descripcion_roles_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='permisos',
            field=models.JSONField(blank=True, default=[1, 2, 3, 4, 5, 6, 7, 8, 9]),
        ),
    ]
