# Generated by Django 5.2.8 on 2025-11-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_crear_roles_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='permisos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
