# Generated by Django 5.2.8 on 2025-11-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0007_producto_esta_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='Productos.producto')),
            ],
        ),
    ]
