# Generated by Django 5.2.5 on 2025-11-18 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('GUIA', 'Guía de Despacho'), ('BOLETA', 'Boleta')], max_length=20)),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.proveedor', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.ingreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='ingreso',
            name='productos',
            field=models.ManyToManyField(related_name='ingresos', through='Movimientos.MovimientoIngreso', to='Productos.producto'),
        ),
        migrations.CreateModel(
            name='MovimientoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('productos', models.ManyToManyField(related_name='salidas', through='Movimientos.MovimientoSalida', to='Productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='movimientosalida',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.salida'),
        ),
    ]
