# Generated by Django 5.2.8 on 2025-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='numero_documento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
