# Generated by Django 5.2.5 on 2025-11-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta')], max_length=20),
        ),
    ]
