# Generated by Django 5.2.8 on 2025-11-27 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0002_alter_ingreso_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='numero_documento',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento debe tener exactamente 8 dígitos numéricos.', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta')], max_length=10),
        ),
    ]
