# Generated by Django 5.2.8 on 2025-11-27 04:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0003_alter_ingreso_numero_documento_and_more'),
        ('login', '0005_alter_roles_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.usuarios', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='salida',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.usuarios', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='movimientoingreso',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='movimientosalida',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
