# Generated by Django 5.2.8 on 2025-12-04 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0004_ingreso_usuario_salida_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='numero_documento',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento debe ser un valor numérico.', regex='^\\d+$')]),
        ),
    ]
