# Generated by Django 5.2.8 on 2025-11-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('ml', 'ml'), ('kg', 'kg')], default='kg', max_length=50),
        ),
    ]
