# Generated by Django 5.2.8 on 2025-11-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='umbral',
            field=models.FloatField(default=5),
        ),
    ]
