# Generated by Django 5.2.8 on 2025-11-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_categoria_nombre_alter_proveedor_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
    ]
