# Generated by Django 5.2.8 on 2025-11-24 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_rename_cantidad_producto_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.ubicacion')),
            ],
        ),
    ]
