# Generated by Django 5.2.8 on 2025-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_rename_cantidad_producto_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
    ]
