# Generated by Django 5.2.8 on 2025-11-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_ubicacionproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UbicacionProducto',
        ),
    ]
